
Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.56.30"
  
    config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
      vb.memory = "1600"
    end

config.vm.provision "shell", path: "lamp.sh/"

end
